const items = [
  // Flipflop (10)
  { name: "Sparx", price: 99, description: "Everyday comfort with soft sole.", image: "ASimage/flipflop1.jpeg", category: "Flipflop" },
  { name: "Paragon", price: 109, description: "Striking stripes and durable straps.", image: "ASimage/flipflop2.jpeg", category: "Flipflop" },
  { name: "Relaxo", price: 119, description: "Light and airy for summer days.", image: "ASimage/flipflop3.jpeg", category: "Flipflop" },
  { name: "Flite", price: 125, description: "Slip-resistant sole for wet areas.", image: "ASimage/flipflop4.jpeg", category: "Flipflop" },
  { name: "VKC Pride", price: 115, description: "Trendy prints to match your style.", image: "ASimage/flipflop5.jpeg", category: "Flipflop" },
  { name: "SoleMate", price: 130, description: "Gentle padding for long wear.", image: "ASimage/flipflop6.jpeg", category: "Flipflop" },
  { name: "Campus", price: 135, description: "Perfect for pool and shower.", image: "ASimage/flipflop7.jpeg", category: "Flipflop" },
  { name: "Bata", price: 125, description: "Bright tones for your wardrobe.", image: "ASimage/flipflop8.jpeg", category: "Flipflop" },
  { name: "Action", price: 110, description: "Perfect for daily errands.", image: "ASimage/flipflop9.jpeg", category: "Flipflop" },
  { name: "Liberty", price: 140, description: "Smooth and stylish movement.", image: "ASimage/flipflop10.jpeg", category: "Flipflop" },

  // Crocs (10)
{ name: "Crocs", price: 299, description: "Breathable design with soft sole.", image: "ASimage/crocs1.jpeg", category: "Crocs" },
{ name: "Wildcraft", price: 310, description: "Sleek black with snug fit.", image: "ASimage/crocs2.jpeg", category: "Crocs" },
{ name: "Puma", price: 320, description: "Extra ventilation for hot days.", image: "ASimage/crocs3.jpeg", category: "Crocs" },
{ name: "Skechers", price: 330, description: "Waterproof and easy to clean.", image: "ASimage/crocs4.jpeg", category: "Crocs" },
{ name: "Nike", price: 340, description: "Add fun colors to your day.", image: "ASimage/crocs5.jpeg", category: "Crocs" },
{ name: "Adidas", price: 345, description: "Extra padded for comfort.", image: "ASimage/crocs6.jpeg", category: "Crocs" },
{ name: "Reebok", price: 350, description: "Street-ready style and comfort.", image: "ASimage/crocs7.jpeg", category: "Crocs" },
{ name: "Woodland", price: 360, description: "Bend and move with ease.", image: "ASimage/crocs8.jpeg", category: "Crocs" },
{ name: "Power", price: 290, description: "Colorful and playful designs.", image: "ASimage/crocs9.jpeg", category: "Crocs" },
{ name: "Lee Cooper", price: 305, description: "Lightweight and durable.", image: "ASimage/crocs10.jpeg", category: "Crocs" },


{ name: "Elegant Touch", price: 1299, description: "Pointed toe with ankle strap for formal events.", image: "ASimage/heels1.jpeg", category: "Heels" },
{ name: "Evening Glow", price: 1499, description: "Sparkly upper with cushioned insole.", image: "ASimage/heels2.jpeg", category: "Heels" },
{ name: "Grace Walk", price: 1399, description: "Medium-height heel with soft suede finish.", image: "ASimage/heels3.jpeg", category: "Heels" },
{ name: "Charm Step", price: 1199, description: "Block heel with open-toe elegance.", image: "ASimage/heels4.jpeg", category: "Heels" },
{ name: "Midnight Glitz", price: 1699, description: "Glitter heel perfect for parties.", image: "ASimage/heels5.jpeg", category: "Heels" },
{ name: "Smooth Motion", price: 1099, description: "Slip-on design with smooth leather look.", image: "ASimage/heels6.jpeg", category: "Heels" },
{ name: "Gloss Finish", price: 1599, description: "Patent finish with slingback style.", image: "ASimage/heels7.jpeg", category: "Heels" },
{ name: "Starlight Walk", price: 1799, description: "Stylish heel with rhinestone detailing.", image: "ASimage/heels8.jpeg", category: "Heels" },
{ name: "Urban Edge", price: 1499, description: "Trendy and modern for casual outings.", image: "ASimage/heels9.jpeg", category: "Heels" },
{ name: "Velvet Curve", price: 1399, description: "Velvet texture with padded footbed.", image: "ASimage/heels10.jpeg", category: "Heels" },

{ name: "Hawai", price: 150, description: "Simple and soft sole.", image: "ASimage/normalwear1.jpeg", category: "Normal Wear" },
{ name: "Relaxo", price: 155, description: "Daily use for relaxed feet.", image: "ASimage/normalwear2.jpeg", category: "Normal Wear" },
{ name: "Sparx", price: 160, description: "Sturdy and long-lasting.", image: "ASimage/normalwear3.jpeg", category: "Normal Wear" },
{ name: "Paragon", price: 165, description: "Foam padding for home use.", image: "ASimage/normalwear4.jpeg", category: "Normal Wear" },
{ name: "Bata", price: 145, description: "No-frills basic utility.", image: "ASimage/normalwear5.jpeg", category: "Normal Wear" },
{ name: "VKC", price: 170, description: "Fun patterns for indoor wear.", image: "ASimage/normalwear6.jpeg", category: "Normal Wear" },
{ name: "SoleMate", price: 155, description: "Perfect for bathroom use.", image: "ASimage/normalwear7.jpeg", category: "Normal Wear" },
{ name: "Action", price: 175, description: "Keeps feet warm at home.", image: "ASimage/normalwear8.jpeg", category: "Normal Wear" },
{ name: "Liberty", price: 165, description: "Extremely lightweight build.", image: "ASimage/normalwear9.jpeg", category: "Normal Wear" },
{ name: "Flite", price: 160, description: "Textile top with foam sole.", image: "ASimage/normalwear10.jpeg", category: "Normal Wear" },

{ name: "Woodland", price: 299, description: "Custom fit straps.", image: "ASimage/sandals1.jpeg", category: "Sandals" },
{ name: "Metro", price: 315, description: "Ideal for trails and treks.", image: "ASimage/sandals2.jpeg", category: "Sandals" },
{ name: "Red Chief", price: 325, description: "City life comfort & look.", image: "ASimage/sandals3.jpeg", category: "Sandals" },
{ name: "SoleMate", price: 280, description: "Light & water-resistant.", image: "ASimage/sandals4.jpeg", category: "Sandals" },
{ name: "Action", price: 340, description: "Leather sandals for events.", image: "ASimage/sandals5.jpeg", category: "Sandals" },
{ name: "Liberty", price: 330, description: "Double strap for grip.", image: "ASimage/sandals6.jpeg", category: "Sandals" },
{ name: "Relaxo", price: 310, description: "Easy to wear Velcro grip.", image: "ASimage/sandals7.jpeg", category: "Sandals" },
{ name: "Bata", price: 345, description: "Rough use for hills.", image: "ASimage/sandals8.jpeg", category: "Sandals" },
{ name: "Paragon", price: 290, description: "Lightweight daily use.", image: "ASimage/sandals9.jpeg", category: "Sandals" },
{ name: "Walkaroo", price: 335, description: "Modern design & fit.", image: "ASimage/sandals10.jpeg", category: "Sandals" },

  
 { name: "Cloud Step", price: 499, description: "Soft foam footbed for ultra comfort.", image: "ASimage/slides1.jpeg", category: "Slides" },
{ name: "Urban Drift", price: 549, description: "Textured sole for superior grip.", image: "ASimage/slides2.jpeg", category: "Slides" },
{ name: "Daily Ease", price: 399, description: "Minimalist design for everyday wear.", image: "ASimage/slides3.jpeg", category: "Slides" },
{ name: "Mono Flow", price: 599, description: "Single-band upper with clean finish.", image: "ASimage/slides4.jpeg", category: "Slides" },
{ name: "Aqua Walk", price: 449, description: "Water-resistant and lightweight.", image: "ASimage/slides5.jpeg", category: "Slides" },
{ name: "Comfort Line", price: 479, description: "Padded top strap with arch support.", image: "ASimage/slides6.jpeg", category: "Slides" },
{ name: "Grip Glide", price: 529, description: "Anti-slip sole ideal for wet surfaces.", image: "ASimage/slides7.jpeg", category: "Slides" },
{ name: "Zen Motion", price: 569, description: "Relaxed fit with breathable material.", image: "ASimage/slides8.jpeg", category: "Slides" },
{ name: "Quick Ease", price: 489, description: "Slip-on comfort with sporty design.", image: "ASimage/slides9.jpeg", category: "Slides" },
{ name: "Street Float", price: 599, description: "Stylish and cushioned for all-day use.", image: "ASimage/slides10.jpeg", category: "Slides" },

{ name: "Silken Step", price: 1399, description: "Elegant design with soft suede finish.", image: "ASimage/blockheel1.jpeg", category: "Block Heel" },
{ name: "Twilight Charm", price: 1499, description: "Square toe and secure ankle buckle.", image: "ASimage/blockheel2.jpeg", category: "Block Heel" },
{ name: "Luxe Line", price: 1599, description: "Premium build with glossy texture.", image: "ASimage/blockheel3.jpeg", category: "Block Heel" },
{ name: "Even Tone", price: 1299, description: "Neutral colors to match any outfit.", image: "ASimage/blockheel4.jpeg", category: "Block Heel" },
{ name: "Classic Curve", price: 1449, description: "Smooth finish with sturdy block base.", image: "ASimage/blockheel5.jpeg", category: "Block Heel" },
{ name: "Midnight Balance", price: 1549, description: "Comfortable height with secure strap.", image: "ASimage/blockheel6.jpeg", category: "Block Heel" },
{ name: "Elegance Rise", price: 1399, description: "Perfect for long occasions with padded footbed.", image: "ASimage/blockheel7.jpeg", category: "Block Heel" },
{ name: "Shadow Grace", price: 1699, description: "Textured block heel with sleek upper.", image: "ASimage/blockheel8.jpeg", category: "Block Heel" },
{ name: "Bliss Edge", price: 1349, description: "Soft lining with matte leather vibe.", image: "ASimage/blockheel9.jpeg", category: "Block Heel" },
{ name: "Soft Motion", price: 1429, description: "Low-profile block heel for everyday elegance.", image: "ASimage/blockheel10.jpeg", category: "Block Heel" },

{ name: "Bata", price: 850, description: "Classic lace-up formal shoes.", image: "ASimage/formal1.jpeg", category: "Formal Shoes" },
{ name: "Red Tape", price: 920, description: "Premium leather finish.", image: "ASimage/formal2.jpeg", category: "Formal Shoes" },
{ name: "Hush Puppies", price: 990, description: "Elegant and smooth leather.", image: "ASimage/formal3.jpeg", category: "Formal Shoes" },
{ name: "Lee Cooper", price: 870, description: "Stylish yet comfortable.", image: "ASimage/formal4.jpeg", category: "Formal Shoes" },
{ name: "Metro", price: 880, description: "Polished formal touch.", image: "ASimage/formal5.jpeg", category: "Formal Shoes" },
{ name: "Action", price: 830, description: "Durable synthetic material.", image: "ASimage/formal6.jpeg", category: "Formal Shoes" },
{ name: "Clarks", price: 950, description: "Refined look for events.", image: "ASimage/formal7.jpeg", category: "Formal Shoes" },
{ name: "Woodland", price: 910, description: "Tough formal design.", image: "ASimage/formal8.jpeg", category: "Formal Shoes" },
{ name: "Liberty", price: 875, description: "Affordable elegance.", image: "ASimage/formal9.jpeg", category: "Formal Shoes" },
{ name: "Franco Leone", price: 890, description: "Stylish pointed design.", image: "ASimage/formal10.jpeg", category: "Formal Shoes" },

{ name: "Zara", price: 799, description: "Trendy high-street fashion.", image: "ASimage/fashion1.jpeg", category: "Fashion" },
{ name: "H&M", price: 699, description: "Casual style and comfort.", image: "ASimage/fashion2.jpeg", category: "Fashion" },
{ name: "Forever 21", price: 749, description: "Youthful urban outfits.", image: "ASimage/fashion3.jpeg", category: "Fashion" },
{ name: "Levi's", price: 850, description: "Iconic denim brand.", image: "ASimage/fashion4.jpeg", category: "Fashion" },
{ name: "Tommy Hilfiger", price: 999, description: "Preppy and polished fashion.", image: "ASimage/fashion5.jpeg", category: "Fashion" },
{ name: "UCB", price: 820, description: "Bright colors and bold looks.", image: "ASimage/fashion6.jpeg", category: "Fashion" },
{ name: "Pantaloons", price: 730, description: "Latest seasonal trends.", image: "ASimage/fashion7.jpeg", category: "Fashion" },
{ name: "Max", price: 690, description: "Affordable family fashion.", image: "ASimage/fashion8.jpeg", category: "Fashion" },
{ name: "Lifestyle", price: 910, description: "Wide range of apparel.", image: "ASimage/fashion9.jpeg", category: "Fashion" },
{ name: "FabIndia", price: 870, description: "Ethnic and handmade fashion.", image: "ASimage/fashion10.jpeg", category: "Fashion" }
];
