const items = [
  // Flipflop (10)
  { name: "Sparx", price: 99, description: "Everyday comfort with soft sole.", image: "ASimages/flipflop1.jpg", category: "Flipflop" },
  { name: "Paragon", price: 109, description: "Striking stripes and durable straps.", image: "ASimages/flipflop2.jpg", category: "Flipflop" },
  { name: "Relaxo", price: 119, description: "Light and airy for summer days.", image: "ASimages/flipflop3.jpg", category: "Flipflop" },
  { name: "Flite", price: 125, description: "Slip-resistant sole for wet areas.", image: "ASimages/flipflop4.jpg", category: "Flipflop" },
  { name: "VKC Pride", price: 115, description: "Trendy prints to match your style.", image: "ASimages/flipflop5.jpg", category: "Flipflop" },
  { name: "SoleMate", price: 130, description: "Gentle padding for long wear.", image: "ASimages/flipflop6.jpg", category: "Flipflop" },
  { name: "Campus", price: 135, description: "Perfect for pool and shower.", image: "ASimages/flipflop7.jpg", category: "Flipflop" },
  { name: "Bata", price: 125, description: "Bright tones for your wardrobe.", image: "ASimages/flipflop8.jpg", category: "Flipflop" },
  { name: "Action", price: 110, description: "Perfect for daily errands.", image: "ASimages/flipflop9.jpg", category: "Flipflop" },
  { name: "Liberty", price: 140, description: "Smooth and stylish movement.", image: "ASimages/flipflop10.jpg", category: "Flipflop" },

  // Crocs (10)
  { name: "Crocs", price: 1000, description: "Breathable design with soft sole.", image: "ASimages/crocs1.jpg", category: "Crocs" },
  { name: "Wildcraft", price: 3100, description: "Sleek black with snug fit.", image: "ASimages/crocs2.jpg", category: "Crocs" },
  { name: "Puma", price: 3200, description: "Extra ventilation for hot days.", image: "ASimages/crocs3.jpg", category: "Crocs" },
  { name: "Skechers", price: 3330, description: "Waterproof and easy to clean.", image: "ASimages/crocs4.jpg", category: "Crocs" },
  { name: "Nike", price: 3400, description: "Add fun colors to your day.", image: "ASimages/crocs5.jpg", category: "Crocs" },
  { name: "Adidas", price: 3045, description: "Extra padded for comfort.", image: "ASimages/crocs6.jpg", category: "Crocs" },
  { name: "Reebok", price: 3500, description: "Street-ready style and comfort.", image: "ASimages/crocs7.jpg", category: "Crocs" },
  { name: "Woodland", price: 3060, description: "Bend and move with ease.", image: "ASimages/crocs8.jpg", category: "Crocs" },
  { name: "Power", price: 2900, description: "Colorful and playful designs.", image: "ASimages/crocs9.jpg", category: "Crocs" },
  { name: "Lee Cooper", price: 3005, description: "Lightweight and durable.", image: "ASimages/crocs10.jpg", category: "Crocs" },

  // Belt Slipers (10)
  { name: "Red Tape", price: 199, description: "Strong leather with metal buckle.", image: "ASimages/beltsliper1.jpg", category: "Belt Slipers" },
  { name: "Bata", price: 185, description: "Classic brown with textured sole.", image: "ASimages/beltsliper2.jpg", category: "Belt Slipers" },
  { name: "Walkaroo", price: 210, description: "Made for both work and home.", image: "ASimages/beltsliper3.jpg", category: "Belt Slipers" },
  { name: "Lee Cooper", price: 220, description: "Suits formal wear with grip.", image: "ASimages/beltsliper4.jpg", category: "Belt Slipers" },
  { name: "Metro", price: 230, description: "Adjustable buckle for comfort.", image: "ASimages/beltsliper5.jpg", category: "Belt Slipers" },
  { name: "Relaxo", price: 225, description: "Extra cushion on top and bottom.", image: "ASimages/beltsliper6.jpg", category: "Belt Slipers" },
  { name: "Paragon", price: 240, description: "Buckle style with active sole.", image: "ASimages/beltsliper7.jpg", category: "Belt Slipers" },
  { name: "Action", price: 205, description: "Comfortable and classy.", image: "ASimages/beltsliper8.jpg", category: "Belt Slipers" },
  { name: "Liberty", price: 200, description: "Secure wide leather strap.", image: "ASimages/beltsliper9.jpg", category: "Belt Slipers" },
  { name: "SoleMate", price: 215, description: "Two-tone fashion look.", image: "ASimages/beltsliper10.jpg", category: "Belt Slipers" },

  // Normal Wear (10)
  { name: "Hawai", price: 150, description: "Simple and soft sole.", image: "ASimages/normalwear1.jpg", category: "Normal Wear" },
  { name: "Relaxo", price: 155, description: "Daily use for relaxed feet.", image: "ASimages/normalwear2.jpg", category: "Normal Wear" },
  { name: "Sparx", price: 160, description: "Sturdy and long-lasting.", image: "ASimages/normalwear3.jpg", category: "Normal Wear" },
  { name: "Paragon", price: 165, description: "Foam padding for home use.", image: "ASimages/normalwear4.jpg", category: "Normal Wear" },
  { name: "Bata", price: 145, description: "No-frills basic utility.", image: "ASimages/normalwear5.jpg", category: "Normal Wear" },
  { name: "VKC", price: 170, description: "Fun patterns for indoor wear.", image: "ASimages/normalwear6.jpg", category: "Normal Wear" },
  { name: "SoleMate", price: 155, description: "Perfect for bathroom use.", image: "ASimages/normalwear7.jpg", category: "Normal Wear" },
  { name: "Action", price: 175, description: "Keeps feet warm at home.", image: "ASimages/normalwear8.jpg", category: "Normal Wear" },
  { name: "Liberty", price: 165, description: "Extremely lightweight build.", image: "ASimages/normalwear9.jpg", category: "Normal Wear" },
  { name: "Flite", price: 160, description: "Textile top with foam sole.", image: "ASimages/normalwear10.jpeg", category: "Normal Wear" },
  { name: "Puma", price: 165, description: "Extremely lightweight build.", image: "ASimages/normalwear11.jpg", category: "Normal Wear" },
  { name: "Paragon", price: 160, description: "Textile top with foam sole.", image: "ASimages/normalwear12.jpg", category: "Normal Wear" },

  // Sandals (10)
  { name: "Woodland", price: 299, description: "Custom fit straps.", image: "ASimages/sandals1.jpeg", category: "Sandals" },
  { name: "Metro", price: 315, description: "Ideal for trails and treks.", image: "ASimages/sandals2.jpeg", category: "Sandals" },
  { name: "Red Chief", price: 325, description: "City life comfort & look.", image: "ASimages/sandals3.jpeg", category: "Sandals" },
  { name: "SoleMate", price: 280, description: "Light & water-resistant.", image: "ASimages/sandals4.jpeg", category: "Sandals" },
  { name: "Action", price: 340, description: "Leather sandals for events.", image: "ASimages/sandals5.jpeg", category: "Sandals" },
  { name: "Liberty", price: 330, description: "Double strap for grip.", image: "ASimages/sandals6.jpeg", category: "Sandals" },
  { name: "Relaxo", price: 310, description: "Easy to wear Velcro grip.", image: "ASimages/sandals7.jpeg", category: "Sandals" },
  { name: "Bata", price: 345, description: "Rough use for hills.", image: "ASimages/sandals8.jpeg", category: "Sandals" },
  { name: "Paragon", price: 290, description: "Lightweight daily use.", image: "ASimages/sandals9.jpeg", category: "Sandals" },
  { name: "Walkaroo", price: 335, description: "Modern design & fit.", image: "ASimages/sandals10.jpeg", category: "Sandals" },

  // Sneakers (10)
  { name: "Nike", price: 599, description: "Clean white street style.", image: "ASimages/sneakers1.jpg", category: "Sneakers" },
  { name: "Adidas", price: 620, description: "Light and breathable upper.", image: "ASimages/sneakers2.jpg", category: "Sneakers" },
  { name: "Puma", price: 650, description: "Bold platform style.", image: "ASimages/sneakers3.jpg", category: "Sneakers" },
  { name: "Reebok", price: 605, description: "Classic and comfortable.", image: "ASimages/sneakers4.jpg", category: "Sneakers" },
  { name: "Converse", price: 615, description: "Quick wear, casual look.", image: "ASimages/sneakers5.jpg", category: "Sneakers" },
  { name: "Skechers", price: 645, description: "Standout with thick sole.", image: "ASimages/sneakers6.jpg", category: "Sneakers" },
  { name: "Fila", price: 630, description: "Two color modern design.", image: "ASimages/sneakers7.jpg", category: "Sneakers" },
  { name: "New Balance", price: 640, description: "Retro sporty design.", image: "ASimages/sneakers8.jpg", category: "Sneakers" },
  { name: "Campus", price: 610, description: "Affordable daily wear sneaker.", image: "ASimages/sneakers9.jpg", category: "Sneakers" },
  { name: "Sparx", price: 600, description: "Durable with rubber sole.", image: "ASimages/sneakers10.jpg", category: "Sneakers" },
   { name: "Converse", price: 615, description: "Quick wear, casual look.", image: "ASimages/sneakers11.jpg", category: "Sneakers" },
  { name: "Skechers", price: 645, description: "Standout with thick sole.", image: "ASimages/sneakers12.jpg", category: "Sneakers" },

  // Sports Shoes (10)
  { name: "Nike", price: 749, description: "Cushioned sole for long runs.", image: "ASimages/sports1.jpg", category: "Sports Shoes" },
  { name: "Adidas", price: 730, description: "Mesh upper with soft base.", image: "ASimages/sports2.jpg", category: "Sports Shoes" },
  { name: "Puma", price: 720, description: "Flexible and breathable design.", image: "ASimages/sports3.jpg", category: "Sports Shoes" },
  { name: "Skechers", price: 760, description: "Great for gym and training.", image: "ASimages/sports4.jpg", category: "Sports Shoes" },
  { name: "Reebok", price: 740, description: "Performance and durability.", image: "ASimages/sports5.jpg", category: "Sports Shoes" },
  { name: "Campus", price: 695, description: "Everyday sports utility.", image: "ASimages/sports6.jpg", category: "Sports Shoes" },
  { name: "Sparx", price: 710, description: "Affordable and lightweight.", image: "ASimages/sports7.jpg", category: "Sports Shoes" },
  { name: "ASICS", price: 780, description: "Designed for pro runners.", image: "ASimages/sports8.jpg", category: "Sports Shoes" },
  { name: "New Balance", price: 755, description: "Cushioning with support.", image: "ASimages/sports9.jpg", category: "Sports Shoes" },
  { name: "Power", price: 700, description: "Reliable and stylish.", image: "ASimages/sports10.jpg", category: "Sports Shoes" },

  // Formal Shoes (10)
  { name: "Bata", price: 850, description: "Classic lace-up formal shoes.", image: "ASimages/formal1.jpg", category: "Formal Shoes" },
  { name: "Red Tape", price: 920, description: "Premium leather finish.", image: "ASimages/formal2.jpg", category: "Formal Shoes" },
  { name: "Hush Puppies", price: 990, description: "Elegant and smooth leather.", image: "ASimages/formal3.jpg", category: "Formal Shoes" },
  { name: "Lee Cooper", price: 870, description: "Stylish yet comfortable.", image: "ASimages/formal4.jpg", category: "Formal Shoes" },
  { name: "Metro", price: 880, description: "Polished formal touch.", image: "ASimages/formal5.jpg", category: "Formal Shoes" },
  { name: "Action", price: 830, description: "Durable synthetic material.", image: "ASimages/formal6.jpg", category: "Formal Shoes" },
  { name: "Clarks", price: 950, description: "Refined look for events.", image: "ASimages/formal7.jpg", category: "Formal Shoes" },
  { name: "Woodland", price: 910, description: "Tough formal design.", image: "ASimages/formal8.jpeg", category: "Formal Shoes" },
  { name: "Liberty", price: 875, description: "Affordable elegance.", image: "ASimages/formal9.jpeg", category: "Formal Shoes" },
  { name: "Franco Leone", price: 890, description: "Stylish pointed design.", image: "ASimages/formal10.jpeg", category: "Formal Shoes" },

   // Fashion (10)
  { name: "Zara", price: 799, description: "Trendy high-street fashion.", image: "ASimages/fashion1.jpg", category: "Fashion" },
  { name: "H&M", price: 699, description: "Casual style and comfort.", image: "ASimages/fashion2.jpg", category: "Fashion" },
  { name: "Forever 21", price: 749, description: "Youthful urban outfits.", image: "ASimages/fashion3.jpg", category: "Fashion" },
  { name: "Levi's", price: 850, description: "Iconic denim brand.", image: "ASimages/fashion4.jpg", category: "Fashion" },
  { name: "Tommy Hilfiger", price: 999, description: "Preppy and polished fashion.", image: "ASimages/fashion5.jpg", category: "Fashion" },
  { name: "UCB", price: 820, description: "Bright colors and bold looks.", image: "ASimages/fashion6.jpg", category: "Fashion" },
  { name: "Pantaloons", price: 730, description: "Latest seasonal trends.", image: "ASimages/fashion7.jpg", category: "Fashion" },
  { name: "Max", price: 690, description: "Affordable family fashion.", image: "ASimages/fashion8.jpg", category: "Fashion" },
  { name: "Lifestyle", price: 910, description: "Wide range of apparel.", image: "ASimages/fashion9.jpg", category: "Fashion" },
  { name: "FabIndia", price: 870, description: "Ethnic and handmade fashion.", image: "ASimages/fashion10.jpg", category: "Fashion" }
];
